/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1,2,3,5,8,13,21,34,55,89,...
By considering the terms in the Fibonacci sequence whose values do not exceed N, find the sum of the even-valued terms.

Input Format

First line contains T that denotes the number of test cases. This is followed by T lines, each containing an integer, N.

Constraints
1<=T<=10^5
10<=N<=4x10^16

Output Format

Print the required answer for each test case.

Sample Input 0

2
10
100
Sample Output 0

10
44
Explanation 0

For N=0, we have {2,8}, sum is 10.
For N=100, we have {2,8,34}, sum is 44.
*/

#include <math.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <assert.h>
#include <limits.h>
#include <stdbool.h>

//Try 1: 4/6 test cases passed. Failed testcase no 2 and 3. Both shows Segmentation fault.
int main(){
    int t; 
    scanf("%d",&t);
    long long sum[t];
    for(int a0 = 0; a0 < t; a0++){
        long n; 
        scanf("%ld",&n);
        
        long fibo[n];fibo[0]=1;fibo[1]=2;
        long i=0;sum[a0]=2;
        while ((fibo[i]+fibo[i+1])<=n)
        {   fibo[i+2]=fibo[i]+fibo[i+1];
            if(fibo[i+2]%2==0)  sum[a0]+=fibo[i+2];
            i++;
        }  
    }
    for(int a0 = 0; a0 < t; a0++)
        printf("%lld\n",sum[a0]);
    return 0;
}
